sudo: required
dist: trusty

matrix:
  include:
  - os: osx
    osx_image: xcode9.2
    language: node_js
    node_js: "9"
  - os: linux
    services: docker
    language: node_js
    node_js: "9"

cache:
  directories:
  - node_modules
  - app/node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"

addons:
  apt:
    packages:
    - libgnome-keyring-dev
    - icnsutils

before_install:
- |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      echo -e "\e[36m\e[1m—————> BUILD: Installing dependencies for Linux\n"
      sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils;
    fi

install: npm i

script:
- ./build/travis.sh


before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

branches:
  safelist:
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
