sudo: required
dist: trusty

matrix:
  include:
  - os: osx
    osx_image: xcode9.2
    language: node_js
    node_js: "9"
  - os: linux
    services: docker
    language: generic

cache:
  directories:
  - node_modules
  - app/node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"

addons:
  apt:
    packages:
    - libgnome-keyring-dev
    - icnsutils

before_install:
- |
  if [ -n "$TRAVIS_TAG" ]; then
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      sudo apt-get install --no-install-recommends
      -y icnsutils graphicsmagick xz-utils;
    fi
  else
    echo -e "\e[36m\e[1m—————> BUILD: Cancelling for branch ${TRAVIS_BRANCH}\n"
    exit 0
  fi

script:
- |
    echo -e "\e[36m\e[1m—————> BUILD: Triggered for tag ${TRAVIS_TAG}\n"
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker run --rm \
        --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_') \
        -v ${PWD}:/project \
        -v ~/.cache/electron:/root/.cache/electron \
        -v ~/.cache/electron-builder:/root/.cache/electron-builder \
        electronuserland/builder:wine \
        /bin/bash -c "npm i && npm run release -- --linux --win"
    else
      npm run release
    fi


before_cache:
  - rm -rf $HOME/.cache/electron-builder/wine

branches:
  safelist:
  - "/^v\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
